test:
  adapter: postgresql
  database: driverflex_test
  host: localhost
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: driverflex_dev
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
